- type: entity # for goblins
  parent: BaseMindRole
  id: MindRoleGhostRoleTeamFreeAgent
  name: Ghost Role (Team Free Agent)
  components:
  - type: MindRole
    roleType: FreeAgent
  - type: GhostRoleMarkerRole

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleBountyHunter
  name: Bounty Hunter Role
  components:
  - type: MindRole
    roleType: FreeAgent
  - type: GhostRoleMarkerRole
